### ISSUE TITLE
Make it possible to use self-signed/bad certificates

### ISSUE THREAD

**Issue by pimterry** [httptoolkit/feedback#14]
Currently, HTTP Toolkit will reject self-signed or otherwise invalid certificates from the upstream site.

In many cases, devs use self-signed certificates locally, so this can cause problems. As a workaround, you can run the app with certificate verification completely disabled by setting the env var `NODE_TLS_REJECT_UNAUTHORIZED` to `0`. E.g. on Linux:

```bash
export NODE_TLS_REJECT_UNAUTHORIZED=0
httptoolkit
```

A proper solution to this is doable though... Probably by forwarding on certificate issues (e.g. bad hostnames, expired certificates) so they appear in the certificate your browser/client sees and you can handle them as normal, and by signing intercepted but untrusted certificates with our own untrusted CA, to simulate that behaviour too.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
There's now a quick practical fix released for this: certificates from `localhost` servers are now not checked by default, so localhost certificates will always be accepted.

I suspect that solves this for most practical cases, but I'll leave this open for the more general case. In future it's very possible to make the list of trusted hosts configurable in the UI, but I'm probably not going to do that unless somebody specifically says it'd be useful.

If the current solution doesn't work for you, and if either configurable trusted hosts or some other solution would help, let me know!

**Comment by Jarga** [comment]
I have a case in which the all of my site certificates are signed by an in-house CA that is not recognized by Node. I have tried the above environment variable NODE_TLS_REJECT_UNAUTHORIZED=0 however i believe (since i am running in windows) that when the node.js process is spawned that the variable is not passing through to the process that actually needs it (This is kind-of a guess). Being able to add/import custom CA's to the global trust would be useful in these scenarios.

**Comment by pimterry** [comment]
@Jarga Which hostname are you connecting to? Adding certificates dynamically to the internal trust store is a little complicated (from both a tech & UX perspective), whilst whitelisting by host is much easier.

Presumably it's not `localhost`? If so this should work already, so if that's happening this is a bug.

If it is indeed some other name on your network, then at the moment there isn't an easy workaround I'm afraid. I'm planning to add configurable per-hostname whitelisting as a Pro feature imminently though. Would that work for you?

**Comment by Jarga** [comment]
It is a custom domain, so domain whitelisting would probably work. In our case we also have an internal OAuth2 service, so even localhost sites will redirect through a non localhost domain for authentication which currently fails.

**Comment by pimterry** [comment]
Ok @Jarga, I had some time today, so this now exists:

![Screenshot from 2019-08-15 17-46-06](https://user-images.githubusercontent.com/1526883/63107852-fc8a7a00-bf85-11e9-8b32-971f9caee2f2.png)

It's in the Pro settings - you can add as many hosts as you like there, and each will be excluded from all certificate validity checks; self-signed/expired/anything.

The app will need to restart before any changes to this whitelist take effect (it'll prompt you). This has only just been released, so you won't have it quite yet; the new version will download in the background next time you use the app (only takes a few seconds), and this setting will be available the time you open it after that.

I'm going to close this issue as fully resolved now, but if you (or anybody else) need some more complex tools to configure which certificates should be checked, let me know.

**Comment by pmorch** [comment]
Hi,

We have development environment that isn't localhost.

And get the `Error: certificate has expired` with or without `export NODE_TLS_REJECT_UNAUTHORIZED=0`. So apparently that workaround no longer works.

Using an SSH port forward to localhost works and allows me to use the self-signed certificate.

Would be nice if:
* The `export NODE_TLS_REJECT_UNAUTHORIZED=0` workaround (or some other workaround) would work again.
* This was documented somewhere
  * E.g. the `Error: certificate has expired` text was a link to a page describing the localhost thing and that Pro can... yada yada yada.
* The PRO config page was available for non-PRO versions... (Just kidding - I understand how this works...).

Many thanks for a useful utility.

Peter

**Comment by pimterry** [comment]
> E.g. the Error: certificate has expired text was a link to a page describing the localhost thing and that Pro can... yada yada yada.

Fortunately I'm working on exactly that as we speak:

![Screenshot from 2019-10-08 16-48-01](https://user-images.githubusercontent.com/1526883/66406124-67d35400-e9eb-11e9-8890-1df1710abb44.png)

Should be live within the next few hours :smiley:

> The PRO config page was available for non-PRO versions

I'd love to give more features away for free, but the project needs to be sustainable somehow. My current strategy is basically to ensure all essential features are freely available, and a limited set of features you'd only need for serious professional development or extensive use are paid.

Happy to debate on the details, but so far it feels reasonable to me, and it's slowly moving the project towards sustainability.

> I was looking for the version, but apparently that isn't visible in the GUI.

You can see the version by hovering over the HTTP Toolkit logo in the top left. I think that 4.0.0 version file you found is actually the internal Electron version. Hovering over the logo isn't really discoverable, but it shouldn't be something you need often. Mind if I ask why you're looking for it?
