### ISSUE TITLE
HTTP Toolkit Crashed

### ISSUE THREAD

**Issue by fraynaud33** [httptoolkit/feedback#19]
Hello, I install HTTP Toolkit on my Windows 7 professionnal computer.
This computer is protected by company security policies but I'm admin of it and I can install software or open port in the firewall. 
When I launch it, I have this error message (who appears less than 1s...) : 
HTTP Toolkit crashed
Server shutdown unexpectedly with code 1.
Please file an issue at github.com/httptoolkit/feedback
I doesn't found log or other information who can explain this error.
Is it possible to activate more debug log ?
Thanks.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
I have some automated error reporting in place to track these. Apparently there was a server crash 25 minutes ago with the error:

```
Ce programme est bloqué par une stratégie de groupe. Pour plus d'informations, contactez votre administrateur système
```

Does it sound like that could be your issue?

I'm not sure how to fix that I'm afraid. Internally HTTP Toolkit is starting a separate server process ([a localhost HTTP server](https://github.com/httptoolkit/httptoolkit-server) which exposes some functionality to the UI), and for some reason it seems that your system is stopping that process from starting, so you'll need to allow that somehow.

**Comment by fraynaud33** [comment]
Yes, It seems it's my company software security who block this process. Can you tell me which name or files start this separate server process to see if I can configure the authorization to execute ?

**Comment by pimterry** [comment]
The HTTP Toolkit desktop shell on Windows is installed to `%LOCALAPPDATA%\httptoolkit\app-<version>`.

Within that folder, the server executable is started via a script at
`<install dir>\resources\app\httptoolkit-server\bin\httptoolkit-server.cmd`.

When run, that script starts the node server by running either `<install dir>\resources\app\bin\node-10.0.0.exe` (on the first run), or `%LOCALAPPDATA%\httptoolkit-server\client\<version>\bin\node.exe` (after the autoupdate mechanism is set up).

This is part of an autoupdate framework built into [Oclif framework](http://oclif.io), which pulls new server versions automatically and always runs the latest. It's the same as tools like the Heroku CLI. Is that going to cause problems for your whitelisting mechanism?

**Comment by fraynaud33** [comment]
Thanks for your quick response. I forgot that to run software which I install myself, I must force run in administrator mode. And it works. Thanks for your help and sorry for the inconvenience.

**Comment by pimterry** [comment]
Sure, no worries! Thanks for reporting this, hopefully this ticket will help the next person who runs into this issue too :+1:
