### ISSUE TITLE
No interception options available on OSX if spotlight is disabled

### ISSUE THREAD

**Issue by fabiocaccamo** [httptoolkit/feedback#21]
I'm using Mac OS X El Capitan 10.11.6 and this is the scenario on app ready:

![schermata 2019-02-04 alle 10 17 13](https://user-images.githubusercontent.com/1035294/52199367-28ee6c80-2866-11e9-81cc-eee275b9e795.png)

It doesn't see any browser.

**Comment by pimterry** [comment]
Interesting! Thanks for letting me know. The way we find applications to run on OSX is by using `mdfind` to search for bundle ids. Do you have `mdfind` available on your machine?

As an example, we find the path to the built in Apple Terminal using:

```
mdfind kMDItemCFBundleIdentifier=="com.apple.Terminal"
```

If you run that on your machine, what does it return?

**Comment by fabiocaccamo** [comment]
Thank for the quick answer.
This is the output of `mdfind kMDItemCFBundleIdentifier=="com.apple.Terminal"` on my machine:

`mdfind[30268:56473] Metadata.framework [Error]: couldn't get the client port`

**Comment by pimterry** [comment]
It seems that this is because spotlight has been disabled, does that sound plausible? I think https://github.com/Homebrew/legacy-homebrew/issues/27931 is the same issue, and there's some solutions there. Can you try those, and let me know if that works for you?

I'd like to find a way to do this without depending on spotlight, as I'm sure you're not the only one who's turned it off, but I do need to be able to find applications by bundle id. I'll look into it and see what I can come up with.

**Comment by fabiocaccamo** [comment]
@pimterry that's correct, I disabled it for performance reasons.
If you find an alternative way to do it it would be great... or just display an error message into the application.

**Comment by pimterry** [comment]
Ok, I'll see what I can do. I can show an error fairly easily, but I suspect most users who've turned this off themselves won't want to turn it back on, so it's not that helpful. In theory it's possible to fall back to manually searching the Application folder myself on demand, it's just more complicated and potentially slower.

I think you can configure which directories Spotlight indexes. You should be able to run it without any performance issues by disabling every directory (especially any that change frequently), except for Applications, and that might work for you as a workaround.

If not HTTP Toolkit is still usable, it just can't start applications for you automatically. You'll be able to intercept and see traffic for any sources that you manually configure to use it as an HTTP proxy (the details are in the 'Anything' option).

**Comment by pimterry** [comment]
I managed to find a solution to this, and everything should now work as normal with server 0.1.21, even if Spotlight indexing is disabled. if you open the app it'll update in the background, hover over the HTTP Toolkit logo to see the currently running version.

I'll close this now, but feel free to reply here if you see this issue again in future.
