### ISSUE TITLE
Allow editing of live requests & responses

### ISSUE THREAD

**Issue by pimterry** [httptoolkit/feedback#35]
HTTP Toolkit could allow you to pause requests before they're sent, or responses before they're received by the client, and manually edit them before they're sent on.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by simonflk** [comment]
I would :100: go `PRO`, if it had something like https://github.com/LanceGin/Mockman built-in

**Comment by pimterry** [comment]
Some bonus points on this from further email discussion:

Key features:
* respond with a canned response
* vary the response depending on different criteria (e.g. url params/headers)
* create routes with an express-style handler so I could code my own responses on the fly (would be nice if it was also given access to the proxied response so it could modify)
* record proxied responses for later playback

Goal is to create mock endpoints for frontends, run "chaos-monkey"-style tests, work offline, etc.

Mockman does do some of this, but only allows canned responses, and also runs as a standalone server not a proxy so it's not easy to use in any application communicating with multiple services.

**Comment by pimterry** [comment]
An alpha version of this functionality is now released, behind a feature flag for very early testing.

If you'd like access send an email to contact@httptoolkit.tech, and I'll set you up.

Full release coming soon, watch this space.

**Comment by pimterry** [comment]
Fun news: this is now done & released. Marketing site is being updated [as we speak](https://httptoolkit.tech/mock), check it out some screenshots:

Simple HTTP mocking:
![mock-screenshot](https://user-images.githubusercontent.com/1526883/65514040-c6251080-dedc-11e9-8348-40b19d956cc9.png)

More complex rules for errors, timeouts, or forwarding requests elsewhere:
![edit-screenshot](https://user-images.githubusercontent.com/1526883/65514047-c8876a80-dedc-11e9-889a-a98866b92396.png)

Breakpointing and live editing requests:
![breakpoint-screenshot](https://user-images.githubusercontent.com/1526883/65514055-ccb38800-dedc-11e9-9fd4-1826cdc20cce.png)

Thanks for the encouragement @simonflk!
