### ISSUE TITLE
Crash with Chrome Dev channel

### ISSUE THREAD

**Issue by LachlanArthur** [httptoolkit/feedback#38]
The application crashes on startup (immediately after the loading progress bar) with this error message:

![image](https://user-images.githubusercontent.com/1870204/65656678-0fec3300-e064-11e9-887e-e54a53ea2624.png)

> Server crashed with 'Error: Conflict on chrome.channel: "stable" !== "dev"' (1).

(that error toast disappears almost instantly, took a few tries to get a screenshot of it)

The message looks correct in that I have Chrome Dev channel installed.

Does HTTP Toolkit only support the stable Chrome channel?

- Windows 10 Pro x64 - Version 1903 - Build 18362.356
- Chrome Dev - Version 79.0.3921.0 (Official Build) dev (64-bit)

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
> Does HTTP Toolkit only support the stable Chrome channel?

HTTP Toolkit absolutely _should_ support the dev Chrome channel, but it looks like there's a bug with that on Windows here. Browser detection on Windows comes from https://github.com/vweevers/win-detect-browsers/, and that's what's throwing this error.

I've filed an issue there to see if they know what might cause this, and I'll look into it myself too and see if I can work out what's up, or find a workaround for you. Watch this space.

**Comment by pimterry** [comment]
Sorry for the delay, but I recently managed to hunt this down & fix it in win-detect-browsers (https://github.com/vweevers/win-detect-browsers/pull/61) and that was released today in the latest HTTP Toolkit. All variants of Chrome should now work fine, and Chrome conflicts on Windows should be a thing of the past.

Let me know if you hit any other issues. Thanks for the report!
