### ISSUE TITLE
Using a client certificate with HTTPS

### ISSUE THREAD

**Issue by peroxy** [httptoolkit/feedback#40]
Is it possible to use a client certificate with HTTPS? This is something fiddler supports, but I can't seem to get it working with Http Toolkit.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Right now, I don't think so, but it's definitely possible! Here, you're talking to a target server who needs you to authenticate with a client certificate, so HTTP Toolkit would need to know the certificate and where to use it, is that right?

I'm open to building that, but it falls squarely into my Pro feature bucket, as it's an unusual case and it's not required for basic usage. If I built it, would it be something worth paying for, to you?

**Comment by peroxy** [comment]
It’s something I have to use regularly when scraping web content, I would
definitely pay for it if it worked well.

I have found out that only Postman with Postman interceptor chrome
extension works with client certificates and https decryption. Could not
get Fiddler to also decrypt the requests.

Dne čet., 26. sep. 2019 ob 12:26 je Tim Perry <notifications@github.com>
napisal/-a:

**Comment by pimterry** [comment]
Ok, thanks, that's good to know. I'll try to prioritize this soon, watch this space for updates.

**Comment by pimterry** [comment]
@peroxy I've been working on this, I think I've got the backend all in place now, it just needs the configuration to be built into the UI which I should be able to get to in the next week or so.

I wanted to check though: what format is your client certificate in? I'm assuming at the moment that it's PKCS12 (normally a `.pfx` or `.p12` file).

Is that correct in your case? If you have openssl installed, you can check by running

```bash
openssl pkcs12 -in <your certificate file>
```

That will print out the contents of the certificate, if it's in the right format.

**Comment by peroxy** [comment]
They are usually in .pfx format, yes.

I believe Fiddler uses .cer files, so you can export any certificate on
your computer and use it.

**Comment by pimterry** [comment]
Exciting news: client certificates are now supported! Pro users can configure them from the settings page like so:

![Proxy settings screenshot](https://user-images.githubusercontent.com/1526883/66329185-6728b800-e92e-11e9-83b9-543b46fa7a50.png)

Only .pfx for now, but it's quite possible to convert most formats to pfx, e.g. given a PEM-formatted key & cert you can use OpenSSL:

```
openssl pkcs12 -export -out ./my-pfx.pfx -inkey ./my-key.pem -in ./my-cert.pem
```

There's also quite a few [online](https://www.leaderssl.com/tools/ssl_converter) [converters](https://www.sslshopper.com/ssl-converter.html), but I can't speak for their trustworthiness.

Try it out, let me know how it goes :+1:
