### ISSUE TITLE
Unable to see mock tab

### ISSUE THREAD

**Issue by jpmghyston** [httptoolkit/feedback#42]
Hi Tim, Jake here! Not sure if you remember me from your Softwire days :)

I've just downloaded the latest version of HTTP Toolkit for WIndows from your website (HTTP.Toolkit-0.1.14.Setup.exe), and I don't seem to be able to find the mock option:
![image](https://user-images.githubusercontent.com/8642112/65707860-41c1c180-e085-11e9-96b6-3674a2612547.png)
Not sure if there's something simple I'm missing or not - let me know if you'd like any more info.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hey Jake! Long time no see, hope Ghyston's going well (I'm actually likely to be in town around Bristech - we should all catch up).

Anyway, delightfully I suspect this has already fixed itself. I'm that good. 

The UI is a hosted web app, but cached locally (for performance, offline, etc). If you're running on an old version, it won't have the mock tab. You can see the currently running UI, desktop & server versions by hovering over the HTTP Toolkit logo on the left.

The server & UI components within the desktop wrapper update somewhat independently, so if you had a previous install and you've just installed a new desktop on top, that won't automatically update them, _but_ they will update in the background within about 10 seconds of you starting the app. Close it, reopen it, I bet it's there.

If not, hover over the logo and let me know what versions it says, it's totally possible something else weird is going on.

**Comment by jpmghyston** [comment]
Hi Tim,

Yep, you're totally right! Took a couple of restarts but I can now see the Mock tab - thanks!

Would be great to see you, do reach out if you've got some free time and we can grab a coffee or something.

**Comment by pimterry** [comment]
Great! Glad to hear it. Enjoy, and do pass it around team Ghyston. I'll get in touch once I know my plans, but it'd be great to catch up with you all.
