### ISSUE TITLE
Development SSL certs: "Error: unable to verify the first certificate"

### ISSUE THREAD

**Issue by yaykyle** [httptoolkit/feedback#45]
Using "Fresh Chrome" option on macOS:

When accessing a local development site that has a self-signed certificate (which is trusted in the system keychain), we see the error "Error: unable to verify the first certificate".

Let me know what other information I can provide.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hi! Self-signed certificates are automatically accepted for localhost servers by default, but not others. This is available as a pro feature though - there's an option to configure a whitelist of hosts for whom any certificate will be accepted in the pro settings.

It looks like this: ![screenshot](https://user-images.githubusercontent.com/1526883/63107852-fc8a7a00-bf85-11e9-8b32-971f9caee2f2.png)

**Comment by yaykyle** [comment]
Ah ok thank you! :) Excited to have this new tool!

**Comment by pimterry** [comment]
Great - I'll close this for now, let me know if you have any other questions.

**Comment by chenkie** [comment]
Great tool and great feature here! I just purchased.

One piece of feedback––it was unclear that I needed to restart to activate the whitelisted domain. Perhaps some text next to the disk icon will help others in the same scenario :)

<img width="814" alt="Screen Shot 2021-03-20 at 10 09 48 AM" src="https://user-images.githubusercontent.com/1847678/111873019-adc47380-8964-11eb-92dc-3022f690b47b.png">

**Comment by pimterry** [comment]
Thanks @chenkie! Good suggestion, I'll look at making that more obvious.
