### ISSUE TITLE
Stuck loading connected sources.

### ISSUE THREAD

**Issue by camgaertner** [httptoolkit/feedback#59]
Stuck loading connected sources.

I popped open the debugger to check what was the issue. Saw google-analytics.com fail to load. Unblocked it in my hosts file. No change

Saw 
```
intercept:1 Failed to load resource: the server responded with a status of 504 (OK)
```
from (https://app.httptoolkit.tech/intercept).

Stopped there. Here's the full console out. 

```
Account store created
index.js:3529 UI store initialized
index.js:3529 Server settings loaded
www.google-analytics.com/analytics.js:1 Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID
index.js:3529 API store initialized
index.js:3529 Server started
index.js:3529 Config loaded
index.js:3529 Server started on port 8000
index.js:3529 Server store initialized
index.js:3529 Events store initialized
index.js:3529 Rules store initialized
index.js:3529 Interceptor store initialized
index.js:3529 App started, rendering
intercept:1 Failed to load resource: the server responded with a status of 504 (OK)
index.js:3529 Service worker loaded
index.js:3529 Previous server version was 0.1.30
```

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
The connected sources there isn't loading anything as such, it's waiting for a source (an HTTP client) to start sending traffic. You don't need to wait for it, although I can see how the spinner could be confusing!

If you click any of the options on that page to intercept something (a browser, for example) you can start sending & seeing traffic straight away. The getting started docs might be helpful: https://httptoolkit.tech/docs/getting-started/

No need to unblock Google analytics, nothing will break with that disabled. 

Does that make sense? If you intercept something, does everything afterwards work as expected?

**Comment by camgaertner** [comment]
> The connected sources there isn't loading anything as such, it's waiting for a source (an HTTP client) to start sending traffic. You don't need to wait for it, although I can see how the spinner could be confusing!
> 
> If you click any of the options on that page to intercept something (a browser, for example) you can start sending & seeing traffic straight away. The getting started docs might be helpful: https://httptoolkit.tech/docs/getting-started/
> 
> No need to unblock Google analytics, nothing will break with that disabled.
> 
> Does that make sense? If you intercept something, does everything afterwards work as expected?

Thanks for the reply. It makes sense to me. I gave it a try and the connected sources was populated, but I don't see how to redirect requests somewhere else. Maybe this is just for interception?
I ended up doing what I wanted with burp suite, but good luck on the tool, it looks interesting.

**Comment by pimterry** [comment]
> I don't see how to redirect requests somewhere else. Maybe this is just for interception?

There's a 'Mock' tab, which allows you to add rules to mock, redirect or otherwise rewrite HTTP traffic as you'd like. No worries though, glad you solved your problem!
