### ISSUE TITLE
Automatic interception for Edge

### ISSUE THREAD

**Issue by pimterry** [httptoolkit/feedback#6]
---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Implemented for the new [Chromium-based Edge](https://www.microsoftedgeinsider.com) :+1:. Definitely works on Mac & Windows, will likely work out of the box on Linux too, but that hasn't been released yet.

Implementing for non-Chromium Edge isn't practical unfortunately, as it's closely integrated with the OS, but it is possible by intercepting your whole system. Automatic system interception is tracked in #8. Until that's implemented, you can do it manually by importing the certificate system-wide & change your system proxy settings.

**Comment by daluu** [comment]
I assume this may also work automatically for Opera (Chromium-based) as well?

**Comment by pimterry** [comment]
It does - if you have Opera installed, that should work out of the box in HTTP Toolkit today.
