### ISSUE TITLE
Virus total detects trojan sig

### ISSUE THREAD

**Issue by stemixreal** [httptoolkit/feedback#60]
Hi, just fyi. A false-positive I presume.

![image](https://user-images.githubusercontent.com/57687696/75118174-c2560f80-566f-11ea-9bc9-e09b3f2302cf.png)

downloaded from

https://httptoolkit.tech/download/win-exe

**Comment by pimterry** [comment]
Ok, thanks for letting me know! Not sure what's going on there, I'll get in touch with them and see if there's anything more they can tell me.

**Comment by pimterry** [comment]
The NANO Antivirus team have got back to me: they've confirmed this is a false positive, and it'll be fixed in their next update. I'm going to keep this open for now, but I'll close it once virustotal confirms that that change is live.

**Comment by pimterry** [comment]
Now updated, it's once again green across the board:

![Screenshot from 2020-02-27 21-08-21](https://user-images.githubusercontent.com/1526883/75482542-4fb59e80-59a5-11ea-9eaf-bb9ca6478fb1.png)

Thanks again for the report, I'll close this now as resolved. If you or anybody else sees similar issues in future, just let me know.
