### ISSUE TITLE
Why do changes to the Mock "Default Rules" not persist after a restart?

### ISSUE THREAD

**Issue by yazinsai** [httptoolkit/feedback#61]
Got the pro version to mock a certain URL permanently, with a fixed response.

The issue is that the new rule I added gets removed everytime I close and reopen HTTPToolkit. This is even after I add it to "Default Rules":

Before restart:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1846034/75424141-22d79c00-5951-11ea-96e7-cb1a3220142b.png">

After restart (saved rule gone):

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1846034/75424188-371b9900-5951-11ea-95c0-ecf8e4b8b73e.png">

**Comment by pimterry** [comment]
Yes, by default the rules are reset on each startup. As a pro user, you can import/export rules with the buttons in the top right, which lets you reuse them fairly easily.

That said, I can see your point. Import/export is definitely more friction. It resets primarily to give you an easy clean slate, as _unexpectedly_ running the rules you configured for a previous session could be confusing.

I've heard similar comments a couple of times before though, so I'm open to reevaluating this. I'll look into it. It might be something to make configurable, with a toggle at the top of the mock page. Do you have any examples of other tools, and which way they go on this?

**Comment by yazinsai** [comment]
@pimterry thanks for the blazing fast response!

When I saw the rules get reset, my intuition was that this was the case because I hadn't added them to the "Default Rules" -- since those are prepopulated when the app loads.

I found it confusing that even after adding it to the "Default Rules", it still didn't persist. Are you saying there's no difference between default rules and regular ones?

**Comment by pimterry** [comment]
Yes, the only difference is that built-in rules get placed there. The goal is that you can see/edit them if you're interested, but by putting them in an initially collapsed group they stay out of the way the rest of the time. Extra built-in rules are also placed here later, e.g. the Android interceptor adds a rule for requests to `android.httptoolkit.tech/connect` to share configuration with connecting devices.

Other than that it's like any other group of rules, there's no special behaviour. Naming improvements welcome! "Built-in rules" or similar might be clearer.

**Comment by yazinsai** [comment]
Ah, it's clear now. Given this description, I wouldn't have expected to be able to add default rules by dragging them under the "Default rules" header.

I think having a "Persist rules" toggle like you said would do the trick.

**Comment by serusko** [comment]
hi @pimterry i understand that technical challenges behind but for UX, user would like to continue in work, and from User perspective its annoying to repeat this step every time app is opened

**Comment by ElijahLynn** [comment]
Thanks for this issue, I was confused why they rules weren't being saved after restart (even non-default rules). I think persisting after restart is needed, because sometimes computers crash and I just want to get back to what I was doing.

**Comment by pimterry** [comment]
This is now fixed! In the latest release, rules are persistent by default for all Pro users. Your app will update in the background next time it's opened. Enjoy! :rocket:
