### ISSUE TITLE
Request Body Garbled Text

### ISSUE THREAD

**Issue by ianbayne** [httptoolkit/feedback#62]
Hi, thanks for an amazing tool! Exactly what I was looking for in my quest to figure out Cloudinary's API for post requests for large uploads:

I'm running the following Cloudinary SDK for uploading large files and viewing the request in HTTP Toolkit:

```ruby
Cloudinary::Uploader.upload_large(file_path, resource_type: :raw)
```

However, the request body is only appearing as garbled text:

<img width="553" alt="Screen Shot 2020-03-03 at 12 50 49" src="https://user-images.githubusercontent.com/10363087/75741339-a2001200-5d4d-11ea-96a1-ba32efdf4774.png">

Am I doing something wrong? Preemptive thanks!

**Comment by pimterry** [comment]
That really is the body of your request. Your request is being sent as "multipart/form-data", which is the same way it would be sent if it was coming from an HTML form that included a file input. There's some more explanation here: https://stackoverflow.com/questions/8659808/how-does-http-file-upload-work.

In this format, the body is a series of fields, split by a separator (in this case `------RubyFormBoundaryW6N....`). Each field has a name, optionally some headers, and a value. In that screenshot there's one field being sent called "timestamp", with a value of 1583205358, and then a field called "file", with some headers, where the value is the raw binary data of your PDF (e.g. `%PDF-1.3` is the PDF file header, see https://lotabout.me/orgwiki/pdf.html for some details), rendered as unicode (so lots of � anywhere the raw data isn't a valid character). There might also be more form fields at the end of the request, I can't tell from here.

Showing the PDF file data here as unicode text isn't perfect, but it's a useful format for the rest of the body content, and the only other real option would be hex-formatted binary data, which isn't much better!

Hopefully that explains a little about what's happening here. I suspect it doesn't solve your problem though. What exactly are you trying to do?

**Comment by ianbayne** [comment]
Hi @pimterry, thanks very much for the response and detailed explanation. I really appreciate it! What I thought was a garbled request is in fact the encoding file that I was sending. I re-checked and if I scroll down I can indeed see more data for my request.

> What exactly are you trying to do?

I'm using a dependency called [Attachinary](https://github.com/assembler/attachinary) to upload files to [Cloudinary](https://cloudinary.com/), but am having trouble with some of the finer details of uploading. Using one of Cloudinary's SDK's, however (which I mentioned above), I am able to upload files of the size and in the format that I require. My idea was to examine the request sent when using the SDK and see if I couldn't figure out a way to mimic that with Attachinary. However, over the last few days I discovered a solution to my problem through a different avenue and partially thanks to Cloudinary's tech support.

Once again, thanks again for the speedy and in-depth response!

**Comment by pimterry** [comment]
No problem! Glad to hear you got it sorted 👍
