### ISSUE TITLE
Add keyboard shortcut for "clear all" (delete all)

### ISSUE THREAD

**Issue by ElijahLynn** [httptoolkit/feedback#68]
Feature request to add a shortcut for "clear all" (delete all) as I find myself doing this a fair bit and it is time consuming to do it with a mouse. 

Thanks

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Good idea! This fits into some other quick shortcut improvements I was planning soon anyway.

Any thoughts on what the shortcut should be? Some multi-key key combo I think, so it's not too easy to press accidentally. I was considering ctrl-delete, since delete is 'delete the selected request', what do you think?

**Comment by ElijahLynn** [comment]
I like `ctrl + shift + delete`, thanks.

**Comment by pimterry** [comment]
Now shipped, as Ctrl/⌘+Shift+delete

That's along with a selection of other shortcut improvements:

* Moved p/delete to Ctrl+P/Ctrl+Delete and made them work globally (not just when the row is focused)
* Added j/k as global shortcuts for going to the next/previous visible row, so you can hop around the data a little quicker
* Added Ctrl+1/2/3 to switch between the intercept/view/mock pages

Enjoy :smiley:

**Comment by ElijahLynn** [comment]
W00t! Just installed and they all work as expected, the extra 2 are useful additions, well done!

**Comment by strikerlulu** [comment]
@pimterry the delete shortcuts are not working in macos m1

**Comment by pimterry** [comment]
Hi @strikerlulu, I have a MacOS M1 test machine, where I've just tested this and it seems to be working fine. Are you seeing this consistently? Is there anything else unusual about your machine or setup?

**Comment by Farisameen2kp** [comment]
@pimterry Yes, it never worked for me. I just use [raycast](https://www.raycast.com/) on both machines. I have an M1 and an M3. It doesn't work on both. you can see the keystrokes in bottom left corner, What's the quickest way to debug it?

https://github.com/user-attachments/assets/f428f5ad-95b7-4fe9-a7bf-75b5778821a0

**Comment by strikerlulu** [comment]
@pimterry Yes, it never worked for me. I just use [raycast](https://www.raycast.com/) on both machines. I have an M1 and an M3. It doesn't work on both. you can see the keystrokes in bottom left corner, What's the quickest way to debug it?

https://github.com/user-attachments/assets/db31d08e-d22c-41e1-9e5c-7026d2ed4283

**Comment by strikerlulu** [comment]
In MacOS instead shouldn't Cmd+Shift+Backspace also behave like Cmd+Shift+Delete ?
In M1 Delete/Backspace are same button, that might causing the issue
Its working when i press Fn＋Cmd+Delete/Backspace 
verified form here
https://www.toptal.com/developers/keycode

**Comment by pimterry** [comment]
Yes, that'll be it - the shortcut is delete, not backspace. There's no strong reason for that though, and given that modern Macbooks make this awkward (and even mark the backspace key as 'Delete') I'm happy to work around it.

I've just expanded the shortcut, so Cmd+Shift+Backspace will now _also_ work. HTTP Toolkit will update in the background next time you run it, and the following time this should work for you as expected. Thanks for the suggestion @strikerlulu!
