### ISSUE TITLE
Brave: "You cannot visit example.com right now because the website sent scrambled credentials that Brave cannot process"

### ISSUE THREAD

**Issue by ElijahLynn** [httptoolkit/feedback#72]
I setup the system proxy and added `/home/elijah/.config/httptoolkit/ca.pem` to the CA Trust in Brave and Brave does not like it, Brave seems to have a different protection in place than Google Chrome (which works). 

```
NET::ERR_CERT_INVALID

example.com normally uses encryption to protect your information. When Brave tried to connect to example.com this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be example.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Brave stopped the connection before any data was exchanged.

You cannot visit example.com right now because the website sent scrambled credentials that Brave cannot process. Network errors and attacks are usually temporary, so this page will probably work later.
```

![image](https://user-images.githubusercontent.com/1504756/81876124-ca1ea500-9536-11ea-9484-6cb7147da4c7.png)

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by ElijahLynn** [comment]
Here is a screenshot showing the different errors whether trusting or not-trusting the HTTP Toolkit CA. 

![image](https://user-images.githubusercontent.com/1504756/81876958-c0963c80-9538-11ea-8200-1c017d66caea.png)

**Comment by ElijahLynn** [comment]
Here is the rejection error that HTTP Toolkit shows while _trusting_ the HTTP Toolkit CA. 

![image](https://user-images.githubusercontent.com/1504756/81876992-d86dc080-9538-11ea-83db-eb58ba09d11c.png)

**Comment by ElijahLynn** [comment]
I just tried [this suggestion](https://support.google.com/chrome/thread/10551759?hl=en&msgid=27135706) to allow insecure localhost and no cigar. 

![image](https://user-images.githubusercontent.com/1504756/81877132-313d5900-9539-11ea-8b1c-54f009d57961.png)

**Comment by ElijahLynn** [comment]
**Workaround found**: Type `thisisunsafe` on the warning page will trust the CA enough to let HTTP Toolkit work with a warning that still says "Not secure" in the address bar. 

![image](https://user-images.githubusercontent.com/1504756/81877637-71e9a200-953a-11ea-8a65-8218c861ad20.png)

I don't know where this is saved as it persists across tabs and new incognito windows. I tried looking in `chrome|brave://net-internals` but don't see anything there.

**Comment by pimterry** [comment]
You shouldn't need to do this, as HTTP Toolkit has built-in support for Brave now! As of the end of last week. If you launch Brave from the button in HTTP Toolkit, does that work for you? Or is there a reason that that isn't usable in your case?

Internally, that's implemented by passing the `--ignore-certificate-errors-spki-list` flag with the SPKI fingerprint of the cert, see https://github.com/httptoolkit/httptoolkit-server/blob/master/src/interceptors/chromium-based-interceptors.ts#L66. This whitelists it for all traffic. Manually trusting certs otherwise may not work because the cert isn't just used to sign the server traffic, but the proxy connection too, which is slightly different and doesn't get expose by the exact same mechanisms.

If you want to do that for yourself, you'll need your cert's fingerprint, the easiest way might be to launch chrome or Brave via HTTP Toolkit, look about chrome://version, and copy the value from the cli args there.

**Comment by ElijahLynn** [comment]
> You shouldn't need to do this, as HTTP Toolkit has built-in support for Brave now! As of the end of last week. If you launch Brave from the button in HTTP Toolkit, does that work for you? Or is there a reason that that isn't usable in your case?

Thanks, I see Brave as a bundled browser now, yay!

![image](https://user-images.githubusercontent.com/1504756/81987887-61473380-95ef-11ea-9489-70d0f4b84e4b.png)







> Internally, that's implemented by passing the `--ignore-certificate-errors-spki-list` flag with the SPKI fingerprint of the cert, see https://github.com/httptoolkit/httptoolkit-server/blob/master/src/interceptors/chromium-based-interceptors.ts#L66. This whitelists it for all traffic. Manually trusting certs otherwise may not work because the cert isn't just used to sign the server traffic, but the proxy connection too, which is slightly different and doesn't get expose by the exact same mechanisms.
> 
> If you want to do that for yourself, you'll need your cert's fingerprint, the easiest way might be to launch chrome or Brave via HTTP Toolkit, look about chrome://version, and copy the value from the cli args there.

Thanks for explaining these internals! I was able to view the bundled `brave://version` and grab that `--ignore-certificate-errors-spki-list=B1bEhy6Fedu9BMT/FBE0+FRQ1HgO6mxaGZKsKV0wZys=` and add it to the `exec` statement in `/usr/share/applications/brave-browser.desktop`. I tried `brave://restart` but it never fully killed the existing process and I got it working with a reboot. I also deleted the HTTP Toolkit from the CA Trust in Brave and it still works. 



My use case was an installed web app that was already installed on that Brave browser profile so I wanted to use the system proxy on it.

**Comment by pimterry** [comment]
Great! Glad that's sorted :+1:
