### ISSUE TITLE
Startup failed: "Cannot read property 'version' of undefined"

### ISSUE THREAD

**Issue by prankmode** [httptoolkit/feedback#74]
Got above message on startup.

MacOS 10.14.6
HTTP Toolkit: 0.1.8

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Sorry about that, that was a bug that was live briefly just now. It's now fixed.

The app is cached, so next time you start it you'll probably see the same error just once more, whilst it updates in the background. Give it 30s then restart the app again though and you should be all good.

I'll close this now, but do let me know if you're still having any trouble.
