### ISSUE TITLE
Use threads to load the response body in the ui

### ISSUE THREAD

**Issue by PostPollux** [httptoolkit/feedback#75]
At the moment it can happen with big response bodies that the ui freezes for quite a while. 
I for example had intercepted https traffic and one "get" request loads a big .css file (30.000 lines). Ok, maybe this file shouldn't be that big in the first place, but as soon as I click on that request the ui freezes for 4 to 5 seconds until that body is loaded.
For this reason I think it would be nice if the response body gets loaded in a separate thread maybe with a loading spinner in that place so we now there is something loading. This way I would not get annoyed by accidentally clicking a request like this.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Absolutely. That's definitely something that needs doing, it's on my list. It's somewhat more complicated than it sounds unfortunately, but it's definitely coming.

In the meantime, as a workaround, the body decoding & formatting that causes this is only triggered when the response/request body card is actually expanded. If you collapse it, you should be able to examine all the headers etc of these requests with no problems.

I know that's not a complete solution or anything, but it might help with this issue in some cases until a proper fix is in place.

**Comment by pimterry** [comment]
Ok, this is now fixed :tada:. Almost all formatting processing now happens async, so you'll see a spinner whilst that happens, and the UI will remain usable.

Your app will update in the background next time it's started. Give that a go, and do let me know if you have any issues at all.

Thanks for the nudge on this! Good to get that sorted :+1:

**Comment by PostPollux** [comment]
Wow! Now that was fast! Just tested it. Works PERFECT!
And it seem it's not only loading it async in the background but it is also caching now, am I right! So when I now click another request and then back to the big one it is still loaded and doesn't start again spinning. Nice job!
