### ISSUE TITLE
Open saved session

### ISSUE THREAD

**Issue by abbas1511** [httptoolkit/feedback#84]
Cannot open saved .har files and need to depend on other tools for further analysis, if any.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
This already exists, it's available as a [Pro feature](https://httptoolkit.tech/get-pro):

> Import/export mock rules, and code or HARs of collected traffic

There's a button at the bottom of the list of requests to do this:

![Screenshot from 2020-07-03 12-43-09](https://user-images.githubusercontent.com/1526883/86461820-dc44e480-bd2a-11ea-8faa-23076048f96f.png)

I think that means this is resolved, so I'm going to close it for now, but feel free to reopen or shout if that's not quite what you're looking for.

**Comment by abbas1511** [comment]
Got it, import is the thing. I was looking @ "Open File" option. Thanks.
