### ISSUE TITLE
HTTPS interception -- how are you pulling this off?

### ISSUE THREAD

**Issue by pieterdd** [httptoolkit/feedback#89]
I must say, HTTP Toolkit looks very promising! Our QA department sometimes has to mock out API calls to test frontend code and this seems really helpful, especially since you don't have to mess with the manual installation of certificates.

That said, I do wonder how you did the trick. I don't see any browser extensions in the preconfigured browser and I don't seem to find any automatically installed certificates in it... so how does it work? And although this is obviously a very compelling and legit use case, what prevents my regular browsing session from being targeted by a MITM attack?

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pieterdd** [comment]
Nevermind, it's an automatically configured proxy and a custom certificate authority did in fact get installed into the browser. Makes sense!

**Comment by pimterry** [comment]
For Chrome (and other Chromium-based browsers), it's pretty easy: there's a special `--ignore-certificate-errors-spki-list=<fingerprint>` command line flag. If you start the browser using that flag, passing the SPKI fingerprint of a certificate, then the browser will ignore all certificate errors that relate to that certificate.

In practice, you can tell Chrome at startup to blindly trust a specific extra CA certificate, and then that one certificate can MITM all traffic.

The actual code for this is all open-source, Chrome for example is launched here: https://github.com/httptoolkit/httptoolkit-server/blob/master/src/interceptors/chromium-based-interceptors.ts#L53-L68

Every other case (Firefox, Android, command line tools) has a different approach, which you can see if you browse around the repo above, but the basic mechanisms are pretty similar: we inject the certificate at startup, and tell the process/device that it should be trusted for HTTPS traffic. If you don't have access to that mechanism (if you don't control the command line that starts Chrome or CLI tools, you can't write to the Firefox profile direction, the Android device isn't rooted and you can't edit the app, etc) then you can't do that, and requiring that access is what protects you from MITM attacks in general.

Does that answer the question?

**Comment by pieterdd** [comment]
Yes, thanks for elaborating! Thanks Tim!
