### ISSUE TITLE
Better Documentation for list controls

### ISSUE THREAD

**Issue by ahaw022** [httptoolkit/feedback#95]
Hi Guys

I have had a look at the documentation for List Controls and can't seem to find how we would do a multi field query

https://httptoolkit.tech/docs/reference/view-page#the-list-controls 

**For example:** how could I search POST requests that return 200 with google.com 

The simple query (e.g. just putting in www.google.com) work fine but looking to be able to filter out a lot of the CSS / JS etc calls and find the calls I am interested in 

![image](https://user-images.githubusercontent.com/68717289/90353411-779ada80-e089-11ea-9fed-7eb99c73a465.png)

**Comment by pimterry** [comment]
The documentation is correct there, so this isn't a documentation issue. Right now, it's not possible to do more complex filtering like this, it's a simple substring filter over the various message properties.

There is an issue for adding detailed filtering though: #27. I know this is a key feature, I'm definitely intending to get that implemented in the short term now. I'm going to close this issue, but feel free to :+1: #27 or add more feedback there, and you can subscribe to notifications on that issue to hear when this is released.
